runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: static
  http_headers:
    Service-Worker-Allowed: /
- url: /.*
  script: main.app
  secure: always
libraries:
- name: ssl
  version: latest

  
